### PR TITLE
add dummy text

### LINKED ISSUE #4: Add Dummy Text
Add any text in content area.

### PR DESCRIPTION
**Pull request by jwkcpkr**
Okey I'm done #4

### CODE REVIEW

**Review by readable24 — CHANGES_REQUESTED** [review]
Good job! But add dot the end of sentence.

**Review by readable24 — CHANGES_REQUESTED** [review]
Not modified yet.

**Review by jwkcpkr — COMMENTED** [review]
This is a comment by PR author

**Review by readable24 — APPROVED** [review]
ok

**Comment by jwkcpkr** [comment]
before merge request

**Pull request merged**
